# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20180520_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student_id',
            new_name='student',
        ),
    ]
