# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20180520_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
