# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
