# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20180422_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
