# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-25 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0007_remove_teachers_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
