# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_teachers_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='teacher',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
