# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_auto_20180529_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
