# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50)),
                ('student_feedback', models.TextField(max_length=3000)),
                ('references_feedback', models.TextField(max_length=3000)),
            ],
        ),
    ]
